######################## default configuration ####################
baseURL = "https://ibnesachiyar.netlify.app/"
languageCode = "en"
title = "Ibn e Sachiyar | Fabrics Store"
theme = "hargo"
summaryLength = "20"
paginate = 12
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  link = "plugins/fontawesome/css/all.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Gallery"
  URL = "products"
  weight = 1

  [[menu.main]]
  identifier="about"
  name = "About"
  URL = "about"
  weight = 2


  

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Gallery"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 2



  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyB4zRiguMkEC7KS7ozFcUlj5ximsz9c7cM"
mapLatitude = "32.641698"
mapLongitude = "74.205133"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "+923364125630"
email = "sahibzadakazim@gmail.com"
location = "Ibn e Sachiyar Fabrics, Main Bazar Jalalpur Jattan, near Tanda Chowk, Jalalpur Jattan, Gujrat"
# copyright
copyright = "| Copyright &copy; 2021 [Ibnesachiyarfabrics](https://ibnesachiyar.netlify.app) All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "fab fa-facebook"
  link = "https://wa.me/923364125630"

  [[params.social]]
  icon = "fab fa-instagram-square"
  link = "#"

  [[params.social]]
  icon = "fas fa-envelope-square"
  link = "#"

  [[params.social]]
  icon = "fab fa-whatsapp"
  link = "https://wa.me/923364125630"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
