---
label: Product Again
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: pagetype
  type: text
  config:
    required: false
  label: Page Type
- type: datetime
  name: date
  label: Date
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: text
  name: priceBefore
  label: Price Before
- type: text
  name: shortDescription
  label: Short Description
- type: text
  name: productID
  label: Product ID
- type: text
  name: type
  label: Type
- type: field_group_list
  name: images
  label: Images
  fields:
  - type: file
    name: image
    label: Image
pages:
- content/products/dks-101-safwa-digital-karandi-print-shirt-kurti-collection-vol-1-2020-shirt-kurti-kameez.md
- content/products/dks-102-safwa-digital-karandi-print-shirt-kurti-collection-vol-1-2020-shirt-kurti-kameez.md
- content/products/dks-104-safwa-digital-karandi-print-shirt-kurti-collection-vol.md
- content/products/dks-105-safwa-digital-karandi-print-shirt-kurti-collection-vol-1-2020-shirt-kurti-kameez.md
- content/products/dks-106-safwa-digital-karandi-print-shirt-kurti-collection-vol-1-2020-shirt-kurti-kameez.md
- content/products/dks-107-safwa-digital-karandi-print-shirt-kurti-collection-vol-1-2020-shirt-kurti-kameez.md
- content/products/si-10-safwa-impala-3-piece-collection-vol-2-2021.md
- content/products/sk-010-safwa-guzel-karandi-3-piece-collection-vol-1-2021.md
- content/products/skd-010-safwa-digital-cotton-kurti-vol-01-2021.md
- content/products/skd-060-safwa-digital-cotton-kurti-vol-06-2021-1.md
- content/products/skd-060-safwa-digital-cotton-kurti-vol-06-2021.md
- content/products/skd-099-safwa-digital-cotton-kurti-vol-10-2021.md
- content/products/skd-100-safwa-digital-cotton-kurti-vol-10-2021.md
- content/products/skd-104-safwa-digital-cotton-kurti-vol-10-2021.md
- content/products/skd-110-safwa-digital-cotton-kurti-vol-10-2021.md
- content/products/skd-111-safwa-digital-cotton-kurti-vol-10-2021.md
- content/products/skd-113-safwa-digital-cotton-kurti-vol-10-2021.md
- content/products/src-704-safwa-rebon-3-piece-collection-vol-7-2021.md
- content/products/src-705-safwa-rebon-3-piece-collection-vol-7-2021.md
- content/products/src-706-safwa-rebon-3-piece-collection-vol-7-2021.md
- content/products/src-708-safwa-rebon-3-piece-collection-vol-7-2021.md
- content/products/src-709-safwa-rebon-3-piece-collection-vol-7-2021.md
- content/products/stc-21-safwa-tucson-3-piece-collection-vol-2-2021.md
- content/products/stc-22-safwa-tucson-3-piece-collection-vol-2-2021.md
