---
label: product
hide_body: true
fields:
- type: text
  name: title
  label: Title
- type: datetime
  name: date
  label: Date
- type: text
  name: description
  label: Description
- name: productID
  type: text
  config:
    required: false
  label: Product ID
- name: type
  type: text
  config:
    required: false
  label: Type
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
pages:
- content/products/taba-shampoo-2.md
