---
label: Product Again
hide_body: false
fields:
- type: text
  name: title
  label: Title
- name: pagetype
  type: text
  config:
    required: false
  label: Page Type
- type: datetime
  name: date
  label: Date
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: text
  name: priceBefore
  label: Price Before
- type: text
  name: shortDescription
  label: Short Description
- type: text
  name: productID
  label: Product ID
- type: text
  name: type
  label: Type
- type: field_group_list
  name: images
  label: Images
  fields:
  - type: file
    name: image
    label: Image
pages:
- content/products/dks-101-safwa-digital-karandi-print-shirt-kurti-collection-vol-1-2020-shirt-kurti-kameez.md
